---
- src: ansistrano.deploy
  version: 3.3.0

- src: geerlingguy.php-versions
  version: 4.0.2

- src: geerlingguy.php
  version: 3.7.0

- src: geerlingguy.composer
  version: 1.7.6

- src: geerlingguy.nginx
  version: 2.7.0

- src: geerlingguy.mysql
  version: 2.9.5

- src: DavidWittman.redis
  version: 1.2.7

- src: https://github.com/hedii/ansible-role-nginx.git
  version: master
  name: hedii.nginx

- src: https://github.com/hedii/ansible-role-php.git
  version: master
  name: hedii.php

- src: https://github.com/hedii/ansible-role-mysql.git
  version: master
  name: hedii.mysql
